name: Deploy to Kinsta Static Hosting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build site
        run: npm run build
        
      - name: Deploy to Kinsta
        uses: kinsta/static-site-deploy-action@v1
        with:
          api-key: ${{ secrets.KINSTA_API_KEY }}
          site-id: ${{ secrets.KINSTA_SITE_ID }}
          deploy-dir: _site